### ISSUE TITLE
remove create_time and update_time for resources in admin api

### ISSUE THREAD

**Issue by Sn0rt** [apache/apisix#10094]
# Summary information

1. Documentation: Remove the field description that needs to pass in the creation time and update time when creating.
2. delete update_time and create_time from define of admin API .
3. Certificate information is parsed from the certificate body without additional storage.

Actually. we need confrim all of the core resource.

- [x] consumer
- [x] consumer_group
- [x] discovery_nodes
- [x] global_rule
- [x] plugin_config
- [x] plugins
- [x] proto
- [x] route
- [x] service
- [x] ssl
  validity_end
  validity_start
  exptime
- [x] stream_route
- [x] upstream

**Comment by yuluo-yx** [comment]
please assign to me!

**Comment by yuluo-yx** [comment]
## Add Todo List
In addition to the attribute configuration described in the above issue, there are other attributes that need to be deleted.

such as: 
### Consumer Group, 
https://github.com/apache/apisix/blob/e1712368e933087fb136be96902be2864d3c56ea/apisix/schema_def.lua#L959
### Plugin config, 
https://github.com/apache/apisix/blob/e1712368e933087fb136be96902be2864d3c56ea/apisix/schema_def.lua#L945
### Global Rule

**Comment by yuluo-yx** [comment]
### Compatibility Test
After I modified create_time and update_time in resource definition. Because previous users may directly go to the official website to copy the corresponding resource definition, if we update the field, there may be compatibility issues, so we did this test.

But still need to remove part of the test code.

- This part of the code will cause ci to fail, so delete:
https://github.com/apache/apisix/blob/1a7fe40ba982c04e2a06901f942c5d4fc06084c8/t/admin/schema.t#L230

- because script functionality in service and route is removed:
https://github.com/apache/apisix/blob/1a7fe40ba982c04e2a06901f942c5d4fc06084c8/t/script/script.t#L64.

@Sn0rt
