### ISSUE TITLE
apisix java plugin filter help 

### ISSUE THREAD

**Issue by githubxubin** [apache/apisix#10428]
### Description

我正在使用Java开发APISIX的插件，但是在postFilter无法获取到boby，是null的，我目前的版本是 apisix-java-plugin-runner-0.4, and apisix-2.15,我目前不想升级APISIX的版本，如果修改apisix2.15的源码，需要修改哪个文件呢？

I am using Java to develop APISIX plugin, but I cannot get boby in postFilter, it is null. My current version is Apisix-java-plugin-runner -0.4, and Apisix-2.15. I do not want to upgrade the version of APISIX at present. If I modify the source code of apisix2.15, how should I modify it?

### Environment

- APISIX version (run `apisix version`):2.15
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Sn0rt** [comment]
In fact, we do not recommend using Java to develop APISIX plug-ins because java-runner developers lack time for maintenance. If you must use Java, you need to understand APISIX and the runner mechanism very well, otherwise debugging will be very difficult.

If you must develop plug-ins, we recommend using lua, but it requires additional learning. However, with the ecological support of APISIX’s existing plug-in cases, this should be relatively easy.

**Comment by monkeyDluffy6017** [comment]
I will close the issue due to long period of no response, feel free to reopen it
