### ISSUE TITLE
help request: regex_uri in proxy-rewrite is not redirecting to sub-path

### ISSUE THREAD

**Issue by sar009** [apache/apisix#10997]
### Description

I have a simple flask server like below
```python
#!/usr/bin/env python3
from flask import Flask, jsonify

app = Flask(__name__)

@app.route("/sub-path")
def sub_path():
    return jsonify({"success": True})

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=3000)
```

I run the docker images as follow
```shell
docker run -d --name apache-apisix -p 9080:9080 -e APISIX_STAND_ALONE=true apache/apisix
```

I applied the apisix config as follow
```shell
docker exec -i apache-apisix sh -c 'cat > /usr/local/apisix/conf/apisix.yaml <<_EOC_
routes:
  - id: sub
    uri: /api/*
    plugin_config_id: sub
    upstream:
      nodes:
        "host.docker.internal:3000": 1

plugin_configs:
  - id: sub
    plugins:
      proxy-rewrite:
        regex_uri:
          - "^/api/(.*)"
          - "/$1"
#END
_EOC_'
```

when I am requesting the following
```
curl http://127.0.0.1:9080/api/sub-path
```
the request is not being passed to `/sub-path` rather it is being proxied to `/`, I am not sure what's going wrong with `regex_uri`.

### Environment

- APISIX version (run `apisix version`): 3.8.0
- Operating system (run `uname -a`): Linux d48d36dc2d5d 6.5.11-linuxkit
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): openresty/1.21.4.2
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): no
- APISIX Dashboard version, if relevant: no
- Plugin runner version, for issues related to plugin runners: no
- LuaRocks version, for installation issues (run `luarocks --version`): no

**Comment by motongxue** [comment]
I reproduced this scenario and encountered the same issue.

**Comment by motongxue** [comment]
And when I add it using PUT method, the URI can be rewritten normally.
```
curl -i "http://127.0.0.1:9180/apisix/admin/routes" -X PUT -d '
{
  "id": "regex_uri",
  "uri": "/api/*",
  "plugins": {
    "proxy-rewrite": {
        "regex_uri": ["^/api/(.*)", "/$1"]
    }
  },
  "upstream": {
    "type": "issue-test",
    "nodes": {
      "host.docker.internal:3000": 1
    }
  }
}'

```

**Comment by sar009** [comment]
does this mean configuration from API and config file is handled differently?

**Comment by motongxue** [comment]
### Problem Diagnosis:

- When configuring APISIX via Docker and setting the environment variable `-e APISIX_STAND_ALONE=true`, you specified APISIX to run in standalone mode.
- However, it was discovered that APISIX's default configuration file `conf/config.yaml` does not have specific settings for standalone mode, leading APISIX to attempt to connect to etcd.
- This issue was initially unnoticed because my computer environment was previously set up with APISIX according to the official tutorial, and the etcd service was continuously running.

### Problem Manifestation:

- After I stopped the APISIX and etcd Docker containers that were installed based on the official tutorial, without proper configuration of `conf/config.yaml`, the `docker logs -f apache-apisix` command revealed that APISIX continuously attempts to connect to etcd.

### Solution:

- To resolve this issue, it is necessary to configure `conf/config.yaml` to ensure the file is correctly set to support standalone mode.
- After making appropriate modifications to `conf/config.yaml`, APISIX will no longer attempt to connect to etcd but instead load configurations directly from the local file.

conf/config.yaml
```yaml
deployment:
  role: data_plane
  role_data_plane:
    config_provider: yaml
#END
```
### References:

- For more details on the standalone mode, you can refer to the deployment modes section in the APISIX official documentation: [Standalone Mode](https://apisix.apache.org/docs/apisix/deployment-modes/#standalone).
- For the initial installation and configuration of APISIX, you can refer to the official tutorial: [APISIX Quick Start](https://apisix.apache.org/docs/apisix/getting-started/README/).

**Comment by sar009** [comment]
Thanks this helped me. Since I had only refered the readme I didn't knew about `config.yaml`.

**Comment by starsz** [comment]
Thanks for @motongxue 👍.
