### ISSUE TITLE
docs: `plugin_config` support in standalone deployment mode

### ISSUE THREAD

**Issue by mangolost** [apache/apisix#11255]
### Description

We deploy apisix in standalone mode and use apisix.yaml to config our routes. 

Since routes are a lot and the plugins used are similar, we intend to use [plugin_config] to extract commonly used plugin configurations. In this case, we can just use plugin_config_id in [routes] and it appears more consice.

However, it does not work and the request fails with a status code of 503.

We notice that [plugin_config] is not mentioned in official document: https://apisix.apache.org/docs/apisix/3.2/deployment-modes/#standalone. Does is mean that [plugin_config] is not supported in standalone mode and can only be set with Admin API?

Can [plugin_config] be supported in in apisix.yaml with standalone deployment mode?

**Comment by kayx23** [comment]
Hi @mangolost , plugin configs should be supported and you may see the test case here: https://github.com/apache/apisix/blob/master/t/config-center-yaml/plugin-configs.t

I'll be updating the issue to a `docs` issue.

As for the 503, please make sure you have first created the `plugin_config` resource with the ID you would like to reference in routes. The error seems to be caused by referencing to a `plugin_config` ID that does not exist.

<img width="446" alt="image" src="https://github.com/apache/apisix/assets/39619599/cc7bd4c7-7720-4567-b46b-7a595e2c7a16">
