### ISSUE TITLE
feat: As a user, I want to auto creat upstream via service discovery

### ISSUE THREAD

**Issue by jzhao20230918** [apache/apisix#11301]
### Description

hello, 

Is there a way the upstream can be created automatically once a service is discovered by service discovery. As far as I know currently it only can be done manully.

Thanks,

**Comment by nfrankel** [comment]
I think there might be a confusion about the concept of `Upstream`: it represents a pool of instances of your app.

You can explicitly define its `node`, or the service discovery finds the nodes for you. In any case, there's no way the upstream can be defined by APISIX since only you knows how to bind the `upstream` to a `route` or a `Service`.

**Comment by juzhiyuan** [comment]
@jzhao20230918 APISIX supports integration with several Service Discovery components. For example, HashiCorp Consul. Refer to https://docs.api7.ai/apisix/how-to-guide/service-discovery/consul-integration
