### ISSUE TITLE
bug: forward-auth does not return upstream headers to client

### ISSUE THREAD

**Issue by thechromosomes** [apache/apisix#11361]
### Current Behavior

I am trying to return the upstream header, but it is not being passed to the client. 

![image](https://github.com/apache/apisix/assets/48309910/77967199-6372-47d0-ba1b-94fb6c25671f)

### Expected Behavior

upstream headers should be passed to the client.

### Steps to Reproduce

1. Add route
2. Add upstream 
3. Add a forward-auth global plugin with the below config. 
```
{
  "_meta": {
    "disable": false
  },
  "request_method": "GET",
  "ssl_verify": true,
  "upstream_headers": [
    "X-Token"
  ],
  "uri": "https://api-six.free.beeceptor.com/auth"
}
```

### Environment

- APISIX version: 3.9.0
- Operating system: Linux
- OpenResty / Nginx version: openresty/1.25.3.1
- etcd version: 3.5.0
- APISIX Dashboard version: 3.0.1

**Comment by zhoujiexiong** [comment]
Hi @thechromosomes ,

Do you mean the `X-Token` header you specified in `fw-auth.upstream_headers` field should respond to client by upstream service for the case of successfully auth.?

Per the doc(https://apisix.apache.org/docs/apisix/plugins/forward-auth/#attributes)
`fw-auth.upstream_headers` is for forwarding to upstream rather than the response direction.

In the case of authorization fails, we should use `fw-auth.client_headers`.

**Comment by thechromosomes** [comment]
@zhoujiexiong you are correct `fw-auth.upstream_headers` is for forwarding to upstream rather than the response direction. It is working as expected.
