### ISSUE TITLE
bug: missing docker images for 3.10.0 release

### ISSUE THREAD

**Issue by markokocic** [apache/apisix#11532]
### Current Behavior

Latest docker images are available for version 3.9.1

### Expected Behavior

There should be images for the latest release, currently 3.10.0

### Steps to Reproduce

docker pull apache/apisix

### Environment

docker

**Comment by tanmaymohan** [comment]
I have an issue running with the 3.9 version where one of my forward-auth is not working and apisix is unable to read the headers causing an issue in our APIs

The fix was added on 3.10 but I don't see any docker image for it despite it being out for 2 weeks. This is causing issue for us as I use it for production in EKS and delaying our timelines.

**Comment by kayx23** [comment]
Available now https://hub.docker.com/r/apache/apisix/tags
