### ISSUE TITLE
help request:  Support for Separate Ingress Classes for Public and Private DNS Zones in AWS EKS

### ISSUE THREAD

**Issue by MichaelLLC** [apache/apisix#11813]
### Description

I have deployed an AWS EKS cluster and created two DNS zones: one private and one public. I need to deploy Apache APISIX with two separate ingress classes, where each ingress controller processes rules only for its respective DNS zone.

Public Requests: Should be handled by apisix-external.
Private/Internal Requests: Should be handled by apisix-internal.
I am using ApisixRoute CRDs to define the rules, and it is crucial to separate the rules for each APISIX instance to ensure proper routing.

### Environment

- APISIX version (run `apisix version`): 3.11.0
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): openresty/1.25.3.2

**Comment by mikyll** [comment]
Since this is related to Kubernetes/APISIX Ingress Controller (and possibly Helm) I suggest you to migrate this issue on [apache/apisix-ingress-controller](https://github.com/apache/apisix-ingress-controller) or [apache/apisix-helm-chart](https://github.com/apache/apisix-helm-chart) so that it can be addressed properly 🙂
