### ISSUE TITLE
feature: Support follow redirect

### ISSUE THREAD

**Issue by agile6v** [apache/apisix#1226]
When a client request passes through APISIX to upstream, if upstream returns 301 or 302 and then APISIX returns directly to the client by default. The client receives 301 or 302 response and then initiates the request again based on the address specified by Location. Sometimes the client wants APISIX to help it do this, so APISIX can provide this capability to support more scenarios.

**Comment by liuhengloveyou** [comment]
It's a useful feature，we can schedule to implement it.

**Comment by membphis** [comment]
@liuhengloveyou Do you know how to implement this feature?

**Comment by spacewander** [comment]
IMHO, I don't like this idea because it doesn't obey the HTTP "convention". Clients like curl can follow redirect because they are clients, but let the proxy follow the redirect looks bad to me. Is there a strong reason to add this feature?

Considering client request a domain A with A's cookie, and A redirects the Client to domain B.
When client requests to domain B, it will take the B's cookie with it.

If we consume the redirect, there is no way for us to know the domain B's cookie and create a request with the cookie attached.

There will be some trouble with cache and TLS too, maybe something else which haven't come to my mind yet.
