### ISSUE TITLE
request help: compared with openresty ,the qps is lower (turn off keepalive)

### ISSUE THREAD

**Issue by leonardjin** [apache/apisix#1413]

**Comment by moonming** [comment]
A few questions.
- What pressure measurement tool is used and is the cpu of OpenResty and Apache APISIX fully loaded?
- Does OpenResty have keepalive on?
- In Apache APISIX, it is recommended to use the adimn API rather than the nginx configuration file for testing, which skips a lot of Apache APISIX optimization

In your test scenario, there is no routing, plug-ins, etc. for Apache APISIX that would be used, in fact what is being tested is OpenResty itself and there shouldn't be any performance difference.

**Comment by membphis** [comment]
@leonardjin you can run a benchmark by this: https://github.com/apache/incubator-apisix/tree/master/benchmark

if you found the performance is bad, please provide the same information, we need them for confirming.

**Comment by membphis** [comment]
> `turned off the keepalive` 

That is the wrong way, please pay attention to this.

**Comment by leonardjin** [comment]
> > `turned off the keepalive`
> 
> That is the wrong way, please pay attention to this.

in my case, I cannot use the keepalive

**Comment by leonardjin** [comment]
> A few questions.
> 
> * What pressure measurement tool is used and is the cpu of OpenResty and Apache APISIX fully loaded?
> * Does OpenResty have keepalive on?
> * In Apache APISIX, it is recommended to use the adimn API rather than the nginx configuration file for testing, which skips a lot of Apache APISIX optimization
> 
> In your test scenario, **there is no routing, plug-ins, etc. for Apache APISIX** that would be used, in fact what is being tested is OpenResty itself and there shouldn't be any performance difference.

wrk 
or not  keepalive

**Comment by membphis** [comment]
@leonardjin please provide your fully test scripts, we need a simple way to get your problem.
