### ISSUE TITLE
bug: CI failed for master branch

### ISSUE THREAD

**Issue by membphis** [apache/apisix#2342]
https://github.com/apache/apisix/runs/1175893233#step:6:227

```
=====found error log=====
+ cat /usr/local/apisix/logs/error.log
+ exit 1
Error: /28 10:07:26 [error] 21906#21906: *4 [lua] config_etcd.lua:424: failed to fetch data from etcd: failed to read etcd dir,  etcd key: /apisix/routes, context: ngx.timer
Error: /28 10:07:26 [error] 21906#21906: *6 [lua] config_etcd.lua:424: failed to fetch data from etcd: failed to read etcd dir,  etcd key: /apisix/ssl, context: ngx.timer
Error: /28 10:07:26 [error] 21906#21906: *10 [lua] config_etcd.lua:424: failed to fetch data from etcd: failed to read etcd dir,  etcd key: /apisix/services, context: ngx.timer
Error: /28 10:07:26 [error] 21906#21906: *8 [lua] config_etcd.lua:424: failed to fetch data from etcd: failed to read etcd dir,  etcd key: /apisix/global_rules, context: ngx.timer

**Comment by membphis** [comment]
@ Yiyiyimu please take a look at this bug, if we can not fix it soon, we can revert the commit first: https://github.com/apache/apisix/commit/e0ee327c084c41366d6f35a1fdca2394c2a2162b

**Comment by Yiyiyimu** [comment]
Sure fix it

**Comment by Yiyiyimu** [comment]
seems master_luarocks not install etcd v3.4

https://github.com/apache/apisix/runs/1175893233#step:6:26

**Comment by Yiyiyimu** [comment]
@membphis The bug seems not related to this PR. I've already did a full revert but the error still occur.

**Comment by Yiyiyimu** [comment]
Bug fixed. The reason is master_luarocks use the wrong version of etcd. I've got no idea why does the error occur after this PR merged. There seems no reason.

But anyway there is a more problem: currently there are two versions of etcd installed in CI, one is v3.2.17 installed from [apt](https://github.com/apache/apisix/blob/master/.github/workflows/build.yml#L32), and another one, which is what we need, v3.4.x from [source](https://github.com/apache/apisix/blob/master/utils/install-etcd.sh#L20). If we only install from source, we need to manually set daemon files for etcd, which may be ok for CI but not user-friendly at all.

**Comment by Yiyiyimu** [comment]
> But anyway there is a more problem: currently there are two versions of etcd installed in CI, one is v3.2.17 installed from [apt](https://github.com/apache/apisix/blob/master/.github/workflows/build.yml#L32), and another one, which is what we need, v3.4.x from [source](https://github.com/apache/apisix/blob/master/utils/install-etcd.sh#L20). If we only install from source, we need to manually set daemon files for etcd, which may be ok for CI but not user-friendly at all.

I know it would be a bad idea but could we use nohup to replace service or other daemon tools? I noticed the [recommended way for Debian](https://github.com/apache/apisix/blob/master/doc/install-dependencies.md#debian-9--10) is nohup

**Comment by Yiyiyimu** [comment]
@nic-chen @moonming I need some help here
