### ISSUE TITLE
feat: plugin `error-log-logger`, collect error log and report to remote server by `cosocket`

### ISSUE THREAD

**Issue by membphis** [apache/apisix#2410]
all of the error log will be written into local files now.

```
$ ls logs
access.log  error.log
```

we can implement a new plugin which named `error-log-logger`, it'll collect the error log from API: https://github.com/openresty/lua-resty-core/blob/master/lib/ngx/errlog.md

we can report those error log to `syslog-ng` server or HTTP server.

**Comment by dabue** [comment]
@membphis  the plugin will impact all request when it be set, is that ok? and it needs to be initialized during http_init.

**Comment by membphis** [comment]
https://github.com/openresty/lua-nginx-module#lua_capture_error_log

we need to enable this directive first, that is the switch. 

and I think we can call `set_filter_level` in the `init` of plugin. it should be fine.

**Comment by dabue** [comment]
I 'll add a timer which collects error logs and reports  to the server  in the init of plugin when the plugin enabled, because the function is global, not releated the request.
and I'll add a shared-dict variable which will be changed when enable or disable the plugin to  indicate the timer  exit or not.

**Comment by membphis** [comment]
yes, that is the right way. ^_^
