### ISSUE TITLE
how to listen new port

### ISSUE THREAD

**Issue by BlinglingGirl** [apache/apisix#2598]
default listen 9080 port
how to listen other ports

apisix 1.5 version

**Comment by spacewander** [comment]
Add your `node_listen` in conf/config.yaml
https://github.com/apache/apisix/blob/bf44ed124d777ca64c6a5b18459f798e7b71a8a5/conf/config-default.yaml#L23

**Comment by BlinglingGirl** [comment]
for example,
I have 3 node_listen ports 9080 9081 9082.
I only want to set a routing rule matching port 9081.

**Comment by spacewander** [comment]
I guess you can dispatch the rule via Nginx variable `server_port`.
See https://github.com/apache/apisix/blob/master/doc/router-radixtree.md#how-to-filter-route-by-nginx-builtin-variable

Since this is not about the title (`how to listen new port`), I will close this issue. Feel free to open a new issue.
