### ISSUE TITLE
chore: change `consumer_id` to `consumer_name`

### ISSUE THREAD

**Issue by membphis** [apache/apisix#2653]
the `consumer_name` is clearer to undersatand.

to avoid ambiguity, use `consumer_name` instead and remove `consumer_id` in doc and source code.

https://github.com/apache/apisix/search?q=consumer_id

**Comment by HelloBug0** [comment]
In the document `https://github.com/apache/apisix/blob/master/doc/admin-api.md#consumer`, I also find that it's a little confusing when I try to delete consumer like this
```sh
curl http://127.0.0.1:9080/apisix/admin/consumers/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -i -d '
{
    "username":"jack",
    "plugins":{
        "jwt-auth":{
            "key":"user-key",
            "secret":"my-secret-key"
        }
    }
}'

curl http://127.0.0.1:9080/apisix/admin/consumers/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X DELETE -i
HTTP/1.1 404 Not Found
Date: Sat, 14 Nov 2020 05:42:17 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: *
Access-Control-Max-Age: 3600
Server: APISIX web server

{"cause":"\/apisix\/consumers\/1","index":91,"errorCode":100,"message":"Key not found"}
```
It turns out that I have to delete consumer using username `jack` instead of `1`. I think the document should be more clear about this description. What do you think of this? Also I am wandering why use username instead of id to identify a consumer just like `routes`?

**Comment by spacewander** [comment]
@HelloBug0 
The doc won't be so confusing after #2679 is merged.
