### ISSUE TITLE
request help:  temporary buffer

### ISSUE THREAD

**Issue by to2false** [apache/apisix#3020]
### Issue description
I always get the following warning when accessing static resource(js, css etc) , is there any way to set it to fix the problem.
```
an upstream response is buffered to a temporary file /usr/local/apisix/proxy_temp/6/85/0000116856 while reading upstream, client
```

### Environment

* apisix version (cmd: `apisix version`): 2.0
* OS: Centos 7

**Comment by tokers** [comment]
This is because the Nginx upstream module default has a non-zero temp file size configuration:

> 
>
> Syntax:	proxy_max_temp_file_size size;
> Default:	
> proxy_max_temp_file_size 1024m;
> Context:	http, server, location
> When buffering of responses from the proxied server is enabled, and the whole response does not fit into the buffers set by
the proxy_buffer_size and proxy_buffers directives, a part of the response can be saved to a temporary file. This directive sets the maximum size of the temporary file. The size of data written to the temporary file at a time is set by the 
> proxy_temp_file_write_size directive.
> The zero value disables buffering of responses to temporary files.

So when the request is out of in-memory buf, data will be saved into files.

Don't worry it's not a problem.

**Comment by sajin-sadanandan-db** [comment]
> > This is because the Nginx upstream module default has a non-zero temp file size configuration:
> > > Syntax:	proxy_max_temp_file_size size;
> > > Default:
> > > proxy_max_temp_file_size 1024m;
> > > Context:	http, server, location
> > > When buffering of responses from the proxied server is enabled, and the whole response does not fit into the buffers set by
> > > the proxy_buffer_size and proxy_buffers directives, a part of the response can be saved to a temporary file. This directive sets the maximum size of the temporary file. The size of data written to the temporary file at a time is set by the
> > > proxy_temp_file_write_size directive.
> > > The zero value disables buffering of responses to temporary files.
> > 
> > 
> > So when the request is out of in-memory buf, data will be saved into files.
> > Don't worry it's not a problem.
> 
> Hi @tokers , could you please explain "it's not a problem"? Whether it's impact performance(If not why)?

Hi @atealxt , @tokers , i get this issue and i can see performance issues with my GUI. Error message I can see in the log is:
"*1842 an upstream response is buffered to a temporary file". Could you please help me know if this is the root cause for the performance issue that I get? Also, how did you fix this?
