### ISSUE TITLE
bug:  kafka logger plugin - failed to process entries: failed to send data to Kafka topic: not found topic 

### ISSUE THREAD

**Issue by Hcreak** [apache/apisix#3060]
### Issue description
使用kafka logger插件 输出报错failed to process entries: failed to send data to Kafka topic: not found topic 
KAFKA中存在此topic

### Environment

* apisix version (cmd: `apisix version`): apisix-2.1
* OS: centos7

### Minimal test code / Steps to reproduce the issue
”kafka-logger“: {
  "batch_max_size": 1000,
  "broker_list": {
    "t-kafka.default": 9092
  },
  "buffer_duration": 60,
  "inactive_timeout": 5,
  "kafka_topic": "logger",
  "max_retry_count": 1,
  "meta_format": "default",
  "name": "kafka logger",
  "retry_delay": 1,
  "timeout": 3
}

**Comment by spacewander** [comment]
You should provide either a packet capture file or a runnable example.
Just paste the configuration here isn't a "Minimal test code / Steps to reproduce the issue".

**Comment by Hcreak** [comment]
Kafka is deployed in k8s Cluster. And I provide  a packet capture file with apisix and kafka.

[kafka_loggger.zip](https://github.com/apache/apisix/files/5706534/kafka_loggger.zip)

**Comment by spacewander** [comment]
At least we know the correct topic is sent.
The topic-partition relation is maintained inside lua-resty-kafka, the kafka client used by APISIX. Since the problem may happen after sending topic and before returning from https://github.com/apache/apisix/blob/f476d2c3dc68439406a9531fc8b4a2a2d50c1333/apisix/plugins/kafka-logger.lua#L95-L100, I think you need to add log inside lua-resty-kafka, and see what happened inside.

You can start from https://github.com/doujiang24/lua-resty-kafka/blob/dba4dc13a3e00a587a7b206945bc07ab6ec52345/lib/resty/kafka/client.lua#L144

I will be busy in the coming few days, so I may not reply you for several days.

**Comment by membphis** [comment]
the `kafka_topic` is optional field.

@Firstsawyou I think you know this issue, right?

**Comment by Hcreak** [comment]
We set the `ZOOKEEPER_CONNECT` parameter and `ADVERTISED_HOST_NAME` parameter of `kafka` and the `broker_list` parameter of the `kafka_logger` plugin to the form of `IP address`, The problem was solved miraculously.

**Comment by spacewander** [comment]
Good to hear.

> But I saw someone encountering the same problem in issues of lua-resty-kafka project

Where is the issue?

**Comment by Firstsawyou** [comment]
> the `kafka_topic` is an optional field.
> 
> @Firstsawyou I think you know this issue, right?

no, `kafka_topic` is a required field.
