### ISSUE TITLE
docs: need a better doc style for developer

### ISSUE THREAD

**Issue by membphis** [apache/apisix#3195]
https://github.com/apache/apisix/blob/master/doc/plugins/traffic-split.md

It's hard to read.

![image](https://user-images.githubusercontent.com/6814606/103632749-c0dbc000-4f7f-11eb-942f-fe9f926bc82a.png)

**Comment by membphis** [comment]
Here is the reason:

![image](https://user-images.githubusercontent.com/6814606/103633131-45c6d980-4f80-11eb-9261-c7072b5ba711.png)

**Comment by membphis** [comment]
@Firstsawyou Do you have any advice?

**Comment by Firstsawyou** [comment]
> @Firstsawyou Do you have any advice?

We need to adjust the length of the `Name` field in `Attributes`. Just keep the main part. For example, `rules.weighted_upstreams.upstream.upstream_host` we can change to `upstream.upstream_host`. Because they all have the same `rules.weighted_upstreams` part.

I think the final form:

| Name             | 
| ---------------- |
| match      | 
| match.vars |
| weighted_upstreams  | 
| upstream_id  |
| upstream   | 
| upstream.type | 
| upstream.nodes  |
| upstream.timeout  |
| upstream.pass_host |
| upstream.name      |
| upstream.upstream_host |
| weight |

This is more clear. what do you think?
