### ISSUE TITLE
bug: OpenResty not found. 

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [apache/apisix#3455]
### Environment

* apisix version (cmd: `apisix version`): current master 
* OS: (cmd: `uname -a`): Fedora 33, AArch64 
* OpenResty / Nginx version: (cmd: `nginx -V` or `openresty -V`): current master 
* etcd version, if have: (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API)
* apisix-dashboard version, if have:

### Minimal test code / Steps to reproduce the issue

1. build openresty 
2. export PATH=/usr/local/openresty/bin:/usr/local/openresty/nginx/sbin:$PATH 

### What's the actual result? (including assertion message & call stack if applicable)
sudo make VERBOSE=1 -j$(nproc) install
which: no openresty in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/lib/snapd/snap/bin)
which: no nginx in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/lib/snapd/snap/bin)
ERROR: OpenResty not found. You have to install OpenResty and add the binary file to PATH before install Apache APISIX.
exit 1
make: *** [Makefile:37: default] Error 1

### What's the expected result?
It works ... Thanks.

**Comment by spacewander** [comment]
You should add the path of OpenResty to your root user's `$PATH` instead of yours, as you call `make` with the sudo.

BTW, although you don't tell us why you use `make install`, you should not use `make install` which is used internally only. There is a comment near it.

Please allow the instructions: https://github.com/apache/apisix/blob/master/doc/how-to-build.md

**Comment by spacewander** [comment]
Or use `sudo --preserve-env=PATH ...`.
