### ISSUE TITLE
Do you have any development plans to get config data even when etcd is down, such as saving configuration files

### ISSUE THREAD

**Issue by aiyiyi121** [apache/apisix#3902]
No. If people use etcd as the data source and it is down, there is no other way to get the configured data.

_Originally posted by @spacewander in https://github.com/apache/apisix/issues/3878#issuecomment-803847848_

I think etcd is an additional dependency, so when it is down，I feel very dangerous.
Do you have any development plans to get config data even when etcd is down, such as saving configuration files.

**Comment by spacewander** [comment]
At least not in the near future.
It is hard to get it right.

**Comment by tokers** [comment]
In a production environment, multiple nodes (typically `3` or `5` nodes) ETCD cluster is desired, due to Raft consensus algorithm, it's not common if whole nodes in the cluster are down together, unless the networking is partitioned. Even in such a case, it doesn't influence APISIX's behavior since APISIX caches all config data in its per-worker process memory.
