### ISSUE TITLE
Could GitHub Action support running CI on ARM?

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix#4156]
### Issue description

GitHub Actions makes it easier to automate builds test, and deploy developer workflow for projects on any OS, language, and cloud. But does it support running CI on ARM-based hardware?

### Environment

None

**Comment by Yiyiyimu** [comment]
Hi @tao12345666333 do you got any progress these days

I tried to look into this problem and failed to find the optimal choice. Here's what I found:
1. First of all, Github Actions have not and seems not to support arm machine as of Service in near future. It seems qemu could be a feasible plan but I can't find people really using it in this kind of situation, and qemu would definitely introduce quite much performance lost when running test, so I **guess** it might not work
2. Of course Github Actions support self-hosted runner, but unluckily Azure does not support arm based VM, so does GCP. AWS have ["graviton processor"](https://aws.amazon.com/ec2/graviton/?nc1=h_ls) which is basically arm64 EC2. But since do not have official AWS account, we might need extra efforts for using it.
3. Since Azure is our primary cloud platform and with the help of Microsoft trying to import Azure into Github, Azure pipeline is also a good choice. And a good news is Azure pipeline [announced](https://azure.microsoft.com/en-us/updates/azure-devops-pipelines-introduces-support-for-linuxarm64/) it supports arm64. But unluckily I couldn't find any docs about how to enable it (find some other also complained about this..). But since we could find envoy is [using it for arm CI](https://www.cncf.io/blog/2020/08/12/cncf-project-envoy-enables-arm64-ci-using-azure-pipelines/), I have totally no idea about it.

**Comment by tao12345666333** [comment]
@Yiyiyimu hi, this issue is divided into two parts

* Build arm image  ref: https://github.com/apache/apisix-docker/pull/165 （I will fix it later）
* Allow CI to run in the arm environment.  I saw this before https://github.com/marketplace/actions/run-on-architecture#supported-platforms

But just like https://github.com/apache/apisix-docker/pull/165#issuecomment-828892611, we cannot use non-official actions.

If we directly use the arm instance, things will be simpler.

**Comment by juzhiyuan** [comment]
> Could we create an AWS account for it

cc @moonming

**Comment by Yiyiyimu** [comment]
> Build arm image ref: apache/apisix-docker#165

Good to know that!

> we cannot use non-official actions

Actually we are allowed to do so with git submodule. And as you said, the larger problem might be the performance loss, so maybe we could wait for an arm64 instance first 😁

**Comment by moonming** [comment]
> > Could we create an AWS account for it
> 
> cc @moonming

I think you can do this in your fork repo instead of apache/apisix. 
what do you think?

**Comment by Yiyiyimu** [comment]
> I think you can do this in your fork repo instead of apache/apisix.
> what do you think?

Hi @moonming Do you mean to test it in the forked repo before applying it to the main repo? If that's it, I could try to test it with my own AWS account at first.

**Comment by moonming** [comment]
yes

Thanks,
Ming Wen
Twitter: _WenMing


Shuyang Wu ***@***.***> 于2021年5月12日周三 上午11:46写道：

**Comment by tao12345666333** [comment]
> I think you can do this in your fork repo instead of apache/apisix.

But if you do this, all the tests have to be synchronized in the forked repo and run?

**Comment by Yiyiyimu** [comment]
> But if you do this, all the tests have to be synchronized in the forked repo and run?

I guess Ming means we'll move ARM test from the forked repo to the main repo after it runs as expected.
