### ISSUE TITLE
request help: jwt-auth: signature mismatch before expiration time

### ISSUE THREAD

**Issue by WeiXue9** [apache/apisix#4983]
### Issue description

I use consumer with jwt-auth plguin,but the token through /apisix/plugin/jwt/sign interface can report signature mismatch before expiration time. 

### Environment

- apisix version 2.6:
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tokers** [comment]
@WeiXue9 Reproduce steps are desired to be shown here so that we can reproduce this situation.

**Comment by tzssangglass** [comment]
you can decode jwt at https://jwt.io/, and see `exp` in jwt payload

**Comment by spacewander** [comment]
Closed as lack of response. Feel free to reopen it if need.

**Comment by fmcodeing** [comment]
I have the same problem

**Comment by spacewander** [comment]
Could you provide reproduce steps?

**Comment by fmcodeing** [comment]
2.9 version&nbsp;&nbsp; 消费者 jwt-auth 这样配置 获取token 后请求&nbsp; 返回 signature mismatch

添加
secret 后 可以正常请求


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/apisix"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月17日(星期五) 下午4:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/apisix] request help: jwt-auth: signature mismatch before expiration time (#4983)





 
Could you provide reproduce steps?
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by spacewander** [comment]
I can't see your steps.
Could you open another issue and paste your steps in text format?
