### ISSUE TITLE
request help:  Does the community have any experience with exposing apisix directly to the public network

### ISSUE THREAD

**Issue by zuiyangqingzhou** [apache/apisix#5220]
### Issue description

![image](https://user-images.githubusercontent.com/17425270/137129199-d02eed6c-907e-47c4-a88f-ad178606ec1e.png)

Our current traffic architecture is shown above on the left, but we want APISIX to fully assume the role of ELB in order to reduce the latency of user requests reaching the service, as shown above on the right. However, we are not sure what risks are associated with doing so, and the known issues are as follows
1. apisix cannot be resiliently scaled
2. apisix is directly exposed to the public network, so does this pose a security risk

I'd like to ask the community if they have experience with this, or if there are any risks that can be predicted in advance here

Thanks

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by shuaijinchao** [comment]
It is not recommended to expose APISIX nodes to the public network because there is a potential risk of being attacked. According to past experience, in the actual production environment, the upper layer of APISIX nodes must have 4-layer load balancing products to ensure the distribution of traffic, the detection of the health status of APISIX nodes, and the high availability of APISIX clusters.

**Comment by zuiyangqingzhou** [comment]
got it, thank you
