### ISSUE TITLE
request help: Request help about prometheus plugin

### ISSUE THREAD

**Issue by shoulda** [apache/apisix#5904]
### Issue description

Using the prometheus plugin collect logs, When the log volume is large, the size of lua_shared_dict prometheus-metrics  will become a bottleneck?

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tzssangglass** [comment]
> Using the prometheus plugin collect logs

The prometheus plugin is not used to collect logs, it is used to collect metrics.

> hen the log volume is large, the size of lua_shared_dict prometheus-metrics will become a bottleneck?

I think you're talking about a large number of total requests, in this case you need to increase the storage space for prometheus-metrics, otherwise you will encounter an error similar to the following: `prometheus.lua:732: log_error(): Unexpected error adding a key: no memory while logging request`, refer to: https://github.com/apache/apisix/issues/3917

BTW,  the prometheus plugin does affect performance by generating long-tail requests, which we are fixing. refer to: https://github.com/apache/apisix/issues/5755

**Comment by shoulda** [comment]
ok , thanks
