### ISSUE TITLE
request help: Apisix deployed on rancher, but not stable

### ISSUE THREAD

**Issue by WeiWANG0118** [apache/apisix#6533]
### Issue description

Hello, 

I deployed Apisix server on rancher, but it's not very stable. 
1. Sometimes apisix server will crash because of a cross-domain problem. I already enabled the global cors plugin. 
2. Sometimes, it will crash because the proxy-rewrite is not working. For information, my upstream will only take uri api/*, my route is v3/api/*, so I used proxy-rewrite plugin to rewrite the uri.  But sometimes the apisix still sends v3/api/* to my upstream. 

PS: there is no errors in errors.log.

### Environment

Cors
```
{
  "allow_origins": "**",
  "allow_methods": "**",
  "allow_headers": "**",
  "expose_headers": "**",
  "max_age": 5,
  "allow_credential": true
}
```
proxy-rewrite
```
"proxy-rewrite": {
      "regex_uri": [
        "^/v3/api/(.*)",
        "/api/$1"
      ],
      "scheme": "https"
    }
```

**Comment by tokers** [comment]
@WeiWANG0118 What's the meaning of crash?

**Comment by tokers** [comment]
> @WeiWANG0118 What's the meaning of crash?

Could you provide the steps for us to reproduce the problem?

**Comment by WeiWANG0118** [comment]
> @WeiWANG0118 What's the meaning of crash?

The server is down.

**Comment by WeiWANG0118** [comment]
> > @WeiWANG0118 What's the meaning of crash?
> 
> Could you provide the steps for us to reproduce the problem?

Actually, I don't know how to reproduce the problem, this error happens occasionally. 🥲

**Comment by angeld287** [comment]
In my case the problem was that I addes the mothod GET in the Route so the CORS continued showing the origin cors error even if i added "GET" in the "allow_methods" cors property. So I changed the 'GET' method for 'ALL' and it worked. So if your case is not the same like mine I recomend that before add some properties in the Route you may test the cors with the default configurations as the documentation does it.
