### ISSUE TITLE
docs: The description of  configuration item "apisix.allow_admin"  ，two official  documents are opposite！

### ISSUE THREAD

**Issue by chenxing0755** [apache/apisix#6566]
### Improved or typo fixed.

1.  one description

apisix source code file：
apache-apisix-2.12.1-src\apache-apisix-2.12.1-src\conf\config-default.yaml
there is a configuration item "apisix.allow_admin"  ，the official description is " # If we don't set any IP list, then any IP access is allowed by default." ，the screenshot below:

![config-default yaml](https://user-images.githubusercontent.com/45444321/157612573-95be5b18-f08c-4988-a2d6-9a9820c7fe97.png)

2. the opposite description
official  website ：https://apisix.apache.org/zh/docs/apisix/FAQ  
the configuration item "apisix.allow_admin" ，the  description is "By default, Apache APISIX only allows 127.0.0.0/24 IP address range to access the Admin API"

![FAQ](https://user-images.githubusercontent.com/45444321/157613976-7a88f23e-1001-4264-b1a8-2be194ae5668.png)

3. Tests have found that，the description of  configuration item "apisix.allow_admin" ， official  website  FAQ is right，the source code file is wrong 。

### Solution

Modify the description of  configuration item "apisix.allow_admin"   in this  source code file "apache-apisix-2.12.1-src\apache-apisix-2.12.1-src\conf\config-default.yaml"

**Comment by leslie-tsang** [comment]
Hello there, APISIX allows CIDR `127.0.0.0/24` access the Admin API, defined by default in [`config-default.yaml`](https://github.com/apache/apisix/blob/530fb4d62c990ec23026f43f70b878e157d441bc/conf/config-default.yaml#L75).
> APISIX will merge [`config.yaml`](https://github.com/apache/apisix/blob/530fb4d62c/conf/config.yaml) with [`config-default.yaml`](https://github.com/apache/apisix/blob/530fb4d62c/conf/config-default.yaml) to generate the final configuration.
the configuration in [`config.yaml`](https://github.com/apache/apisix/blob/530fb4d62c/conf/config.yaml) will take effect rather than [`config-default.yaml`](https://github.com/apache/apisix/blob/530fb4d62c/conf/config-default.yaml) one

-----
If an empty IP list is defined in the configuration, APISIX will reject all traffic to Admin API.

>   allow_admin:                  # http://nginx.org/en/docs/http/ngx_http_access_module.html#allow
    - 127.0.0.0/24              # If we don't set any IP list, then any IP access is allowed by default.

**Comment by tokers** [comment]
> the opposite description
official website ：https://apisix.apache.org/zh/docs/apisix/FAQ
the configuration item "apisix.allow_admin" ，the description is "By default, Apache APISIX only allows 127.0.0.0/24 IP address range to access the Admin API"

By default not means empty but also contains some default settings from APISIX's config-default.yaml.
