### ISSUE TITLE
help request: openid-connect plugin server-side session storage configuration

### ISSUE THREAD

**Issue by mehmetcuneyit** [apache/apisix#6792]
### Description

I see that [lua-resty-openidc](https://github.com/zmartzone/lua-resty-openidc) does the heavy-lifting. I would like to monitor/manage the session cache, and also use another server-side storage mechanisms other than shared-memory(default), e.g. memcache or redis. I'm worried about the shared-memory performance for large number of user sessions(1M+) even after proper scaling.  
- How can I configure APISIX to use redis as the session storage ? 
- Do I need to scale APISIX gateway to manage large number of sessions ?  
- What would you suggest about managing APISIX session storage in multi-cluster environment?
- Overall, what would you suggest about session storage for the production as best practice ?

Any opinion would be appreciated :pray:

### Environment

- APISIX version (run `apisix version`): **2.13.0**
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by spacewander** [comment]
Look like lua-resty-openidc only supports using shared-memory as the cache?
See https://github.com/zmartzone/lua-resty-openidc/blob/a468d13283d62ef5e3d14f02404294f7777c053d/lib/resty/openidc.lua#L102

**Comment by mehmetcuneyit** [comment]
@spacewander I think it is doable. Underlying library [lua-resty-session](https://github.com/bungle/lua-resty-session) supports various options for the session storage ( see [PluggableStorageAdapters](https://github.com/bungle/lua-resty-session#pluggable-storage-adapters) ) . I'm trying to figure out how I can pass the library configurations through (apisix conf yaml OR openid-connect plugin) -> lua-resty-openidc -> lua-resty-session. ( e.g. [regis storage adapter](https://github.com/bungle/lua-resty-session#redis-storage-adapter) )

**Comment by spacewander** [comment]
> How can I configure APISIX to use redis as the session storage

You can refer to https://github.com/bungle/lua-resty-session#redis-storage-adapter and https://github.com/apache/apisix/blob/master/docs/en/latest/customize-nginx-configuration.md. Or you can contribute the code to https://github.com/apache/apisix/blob/master/apisix/cli/ngx_tpl.lua

lua-resty-session puts its configuration in the Nginx conf so we can't update it without reloading Nginx. It would be great if you can submit a PR to it, and make lua-resty-session configurable with Lua code. You can refer to https://github.com/apache/apisix/blob/master/apisix/plugins/limit-count/limit-count-redis-cluster.lua

> Do I need to scale APISIX gateway to manage large number of sessions
> What would you suggest about managing APISIX session storage in multi-cluster environment?

Since APISIX is stateless, we can scale APISIX as needed.

**Comment by mehmetcuneyit** [comment]
@spacewander Temp solution would be like https://the-asf.slack.com/archives/CUC5MN17A/p1652640355608239?thread_ts=1652270452.089599&cid=CUC5MN17A
