### ISSUE TITLE
docs: improve the Deployment Role document

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix#7422]
## Resource

1. Document Link: https://apisix.apache.org/docs/apisix/next/architecture-design/deployment-role/

## Improvements

1. SEO: Missing keywords
2. `Deployment Role`: What's a `Role`? Should it be `options` or `modes`?
3. This document contains a table that explains what's `traditional,` `decoupled,` and `standalone,` but the `description` field misses details.
4. For the `traditional`'s description, it's `DP + CP are deployed together by default. People need to disable enable_admin manually`. How about updating it to `XXXX. This mode enables "enable_admin" by default`?
5. This document mentions `Control Plane`. Some developers will get confused because of the relationship between `Dashboard` and `AdminAPI.`
6. In the `Traditional` section, the diagram shows `Admin API` is listening on the `9180` port, but our document uses `:9080/apisix/admin/XXX` by default. Should we use the same port? Or should we explain why we use a different port?
7. In the `standalone` section, we should also link readers to the `Standalone` document.
8. How about adding more `reasons/benefits for each mode? The readers will know why and which way is suitable for their case.
9. It's an English version only currently, need to translate to Chinese as well. cc @hf400159 

### Desired State

See `Current State`.

**Comment by hf400159** [comment]
1. We can test in different modes so that users can intuitively feel the difference between the three modes.
2. It needs to be confirmed that if this function is released in the next version, it is necessary to explain to the user whether it is possible to directly upgrade the lower version of APISIX to the new version.
3. For `4`, the description is still unclear. Should be: xxx, if you want to achieve independent deployment of CP and DP, you need to disable `enable_admin`.
4. We need a how-to document that tells users how to deploy these three methods, rather than just giving examples of `configuration files`.

**Comment by kayx23** [comment]
Hi - this issue seems outdated. Please re-evaluate and see if this can be closed. Thanks.
