### ISSUE TITLE
bug: if nginx return 499，apisix_latency will equal request_time

### ISSUE THREAD

**Issue by huntkalio** [apache/apisix#7445]
### Current Behavior

if nginx return 499 because client closed the connection before the server answered the request，lua-var-nginx-module upstream_response_time will return 0，but ngx.var.upstream_response_time return right value.
https://github.com/api7/lua-var-nginx-module/issues/10
And 
```
        upstream_latency = ctx.var.upstream_response_time * 1000
        apisix_latency = apisix_latency - upstream_latency
```
would let apisix_latency will equal request_time

### Expected Behavior

apisix_latency don't equal request_time

### Steps to Reproduce

nginx return 499 because client closed the connection before the server answered the request

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by kingluo** [comment]
@huntkalio @spacewander Yes, `upstream_response_time` from lua-var-nginx-module is incorrect.
Because it checks the upstream response status first (the initial value is 0), it would get the response time only when the status is not 0. But in 499 case, the status is 0 because 499 is internal status code but not from upstream.

However, the nginx way is to get the response time ignoreless of the status code.
The solution should be to align with the nginx way.

**Comment by spacewander** [comment]
@kingluo 
Well done. Would you like to submit a PR to fix it?

**Comment by spacewander** [comment]
Done
