### ISSUE TITLE
feat: I want to specify multi xxx.yaml or a conf dir (like nginx include instruction) for apisix router config, can apisix support this by providing start options

### ISSUE THREAD

**Issue by wyaow** [apache/apisix#7470]
### Description

Here, i talk about stand alone mode.
we all know apisix.yaml is the only one router config file.
can we support multi config file. and when we start apisix, we could specify the router config file.

Since many cases, we keep two config files , one for fixed and will not change, and another used for dynamic changes.

**Comment by spacewander** [comment]
We have discussed this before.
Using multiple yaml files in the standalone mode is too complex. It would be easier to solve it in an agent which prepares the yaml file.

**Comment by wyaow** [comment]
> 

In nginx, we can specify a dir to include all *.conf file below
include vhost/*.conf;
can we support this also, I guss it's usefual and common cases.

**Comment by 0x9be00ff1** [comment]
+1, a single standalone apisix instance serves multiple sites, prefer multiple config files or a conf dir

**Comment by wyaow** [comment]
> 
It's common, to let the business team to maintain their own router config, And we should  only add include instruction in apisix.conf.

**Comment by wyaow** [comment]
> @wyaow Could you introduce the backgrounds that why you want such a feature? We do can solve it technically, but we'll be more interested in the cause.

It's common, to let the business team to maintain their own router config, And we should only add include instruction in apisix.conf.

**Comment by gubarba** [comment]
Indeed, IMHO standalone mode cuts out the flexibility that the default mode carries when managing multiple sources of routes configuration ( multiple teams mantaining multiple CRDs defined routes ).I'm trying to undersand whether i should try to use standalone mode, since i'm not willing to operate the ETCD Cluster that the control plane depends on

**Comment by gubarba** [comment]
Indeed, IMHO standalone mode cuts out the flexibility that the default mode carries when managing multiple sources of routes configuration ( multiple teams mantaining multiple CRDs defined routes ) without the need of an external tool.
I'm trying to undersand whether i should try to use standalone mode, but managing a single configmap to configure many websites and projects routes doesn't seem a nice way to go .
Since i'm not willing to operate the ETCD Cluster that the control plane depends on ( I'm on EKS and can't use the cluster's  ETCD, so I have to manage my own ), this would enable scaling the configuration managent on multiple teams scenarios, without the operational overhead of managing the ETCD cluster or other configuration centers ( Consul, etc) and sticking  to kubernetes core features, such as configmaps and volumeMounts.
