### ISSUE TITLE
bug: uploading a cert via api - it is accepted with no error, shows in dashboard with correct SNI, but invalid expiry date. Cert can NOT be deleted

### ISSUE THREAD

**Issue by MarkCupitt** [apache/apisix#8665]
### Current Behavior

uploading a cert via api - it is accepted with no error, shows in dashboard with correct SNI, but invalid expiry date. Cert can NOT be deleted, says cannot find cert with that id

this occurs with PUT (supplied id) AND POST (random id)

Cert is not seen by Routes .. error logged that SNI Can not be found

using simplified JSON  as per examples

```
{
    "cert": cert,
    "key": key,
    "snis": [sni],
}
```

### Expected Behavior

Cert should be displayed with correct expiry date, and can be removed

### Error Logs

BO Error logs

### Steps to Reproduce

Install APi Six via Helm
Upload a cert via admin api

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by MarkCupitt** [comment]
Additional effort still produces same result, 

Bash Script used:

```
  local sslcrt=$(cat "./certs/$sslurl.crt")
  local sslkey=$(cat "./certs/$sslurl.key")
  
  local json=$(cat <<EOF
  {
    "snis": ["${sslurl}"],
    "cert": "${sslcrt}",
    "key": "${sslkey}"
    }
EOF
)

curl -s  http://apisixadminapiurl/apisix/admin/ssls/1 -H "X-API-KEY: $apikey" -X PUT -i -d "$json" # >/dev/null
```
Note on image:

- Cert loaded via APi
- Expiration time not decoded
- SNI Decoded
- Unable to delete. Noted its using /ssl and not ssls

![image](https://user-images.githubusercontent.com/5503184/213591433-2066d6c4-0e73-41f7-abae-5c2bb5196949.png)

**Comment by MarkCupitt** [comment]
So for those struggling with this, Dashboard V2, on ssl certs at least, is NOT compatible at all with apisix V3.x, you **MUST** use the apis.

Documenting for anyone else who may come across this issue

**Comment by ertanci** [comment]
Hi, 
It is solved setting validity_end parameter in body. I am using ansible for these operation.
Using the certificate I was able to obtain the validity_end parameter before calling the API. In order to be clearly understood, I want to add partial code. 

- name: Get the expiration date of the certificate
  command: "openssl x509 -enddate -noout -in /tmp/public.crt"
  register: cert_expiration

- name: Extract date from openssl output
  set_fact:
    expiration_date: "{{ cert_expiration.stdout | regex_replace('notAfter=', '') }}"

- name: Convert expiration date to epoch
  shell: "date -d '{{ expiration_date }}' +%s"
  register: expiration_epoch

- name: Show the expiration date in epoch
  debug:
    msg: "The certificate expires on {{ expiration_date }} which is {{ expiration_epoch.stdout }} in epoch time."

- name: Add ssl list in apisix
  uri:
    url: "https://{{ apix_admin_endpoint }}/apisix/admin/ssls"
    method: POST
    body: |
      {
          "cert": "{{ decoded_cert }}",
          "key": "{{ decoded_key }}",
          "snis": ["{{ apix_snis }}"],
          "validity_end": {{ expiration_epoch.stdout }}
      }
    body_format: json
    headers:
      X-API-KEY: "{{ apisix_key.stdout | trim }}"
      Content-Type: application/json
  register: response
  failed_when: response.status not in [200, 201]
