### ISSUE TITLE
feat: As a user, I want to the consumer support openid-connect plugin as an auth plugin, so that we can use openid-connect plugin to config consumer auth

### ISSUE THREAD

**Issue by Fabriceli** [apache/apisix#8686]
### Description

Hi, guys
 
I found that if enable `openid-connect` plugin in consumer, it will return an error: `require one auth plugin`. 
I want to support the `openid-conenct` as an **auth** plugin, so that we can set up Consumer with `openid-connect` plugin.

Concurrent `auth` plugins in APISIX 3.1.0 version:
![image](https://user-images.githubusercontent.com/13508022/212546810-fe92c230-2494-483d-835a-5815396b7c30.png)

Reference APISIX `openid-connect` plugin [code](https://github.com/apache/apisix/blob/master/apisix/plugins/openid-connect.lua#L140):
```lua
local _M = {
    version = 0.2,
    priority = 2599,
    name = plugin_name,
    schema = schema,
}
```

 [apisix consumer reference code](https://github.com/apache/apisix/blob/master/apisix/admin/consumers.lua#L61):
```lua
local count_auth_plugin = 0
for name, conf in pairs(conf.plugins) do
    local plugin_obj = plugin.get(name)
    if plugin_obj.type == 'auth' then
        count_auth_plugin = count_auth_plugin + 1
    end
end

if count_auth_plugin == 0 then
    return nil, {error_msg = "require one auth plugin"}
end
```

**Comment by tao12345666333** [comment]
cc @soulbird @spacewander

**Comment by spacewander** [comment]
`openid-connect` will get the user info from an external provider. And APISIX's consumer requires to know the user info and bind the auth plugin with them. So there are two questions:
1. How can these two systems sync the user info? What happens if the data mismatch?
2. If the external provider and APISIX have the same user info, why don't we authenticate in APISIX and get rid of external provider?
