### ISSUE TITLE
when the etcd use dns ,will be some error

### ISSUE THREAD

**Issue by kellyseeme** [apache/apisix#8713]
### Description

when the etcd connection is use domain,then in two vm cluster there one have some error
`2023/01/19 11:09:53 [warn] 10007#10007: *10702332 [lua] v3.lua:716: request_chunk(): http://lb-etcd-03.test.com:2379: failed to parse domain: failed to parse domain. Retrying, context: ngx.timer
`
interval have 1min,10min

how this happen ?the dns resolve is good ,becase another vm resolve  is ok.

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by kellyseeme** [comment]
where can i find the lua path?

**Comment by tokers** [comment]
This is a known issue. We're still trying to troubleshoot it.

**Comment by lakewatcher** [comment]
> This is a known issue. We're still trying to troubleshoot it.


I also found the same prompt when using nacos2.2.1. 

May I ask if it is the same issue and if it has also been fixed in 2.15.3？
>在使用nacos的时候也发现了相同的提示。请问是否是同一个问题？也在2.15.3/3.2中修复了？

error message :

2023/05/25 15:50:57 [error] 27732#27732: *846092837 [lua] init.lua:290: get_url:ns/instance/list?healthyOnly=true&serviceName=cuckoo-trade-charge&accessToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuYWNvcyIsImV4cCI6MTY4NTAxOTA1N30.uY_XfO0GDt__8omktWzA6SrxZchLA5f0rhggBJnoJCE&namespaceId=&groupName= err:failed to parse domain: failed to parse domain, context: ngx.timer


or Do I need to raise a new issue？

**Comment by monkeyDluffy6017** [comment]
It's fixed, please refer to this issue: https://github.com/apache/apisix/issues/8800
The related pr: https://github.com/api7/apisix-build-tools/commit/b3805a0bef56abb1cd0e950437168612272a4681
