### ISSUE TITLE
docs: plugin priority

### ISSUE THREAD

**Issue by freemankevin** [apache/apisix#9085]
### Current State

https://apisix.apache.org/docs/apisix/terminology/plugin/#custom-plugin-priority

Custom plugin priority does not apply to the rewrite phase of some plugins configured on the consumer. The rewrite phase of plugins configured on the route will be executed first, and then the rewrite phase of plugins (exclude auth plugins) from the consumer will be executed.

### Desired State

Can you give an example to explain it, it feels a bit confusing, and I don't quite understand what is specifically said here?

**Comment by ro4i7** [comment]
@freemankevin May be this can help:
let's say we have a route in Apisix that has the following plugins configured:

1. The `response-rewrite` plugin with a priority of 10
2. The `cors plugin` with a priority of 20

In this case, the `the response-rewrite` plugin will execute before the `cors` plugin because it has a lower priority value.

Now let's say we also have a consumer that has the following plugins configured:

1. The `request-rewrite` plugin with a priority of 15
2. The `rate-limiting` plugin with a priority of 25

In this case, the `request-rewrite` plugin will execute after the `response-rewrite` and `cors` plugins from the route have executed, because it has a higher priority value than the `response-rewrite` plugin but a lower priority value than the `rate-limiting` plugin.


Overall means, The custom plugin priority applies to the execution order of plugins within a single phase (e.g. all plugins within the rewrite phase of a route), but not across different phases or between plugins from different sources (e.g. plugins configured on a route vs. plugins configured on a consumer).

**Comment by freemankevin** [comment]
thanks.

**Comment by kayx23** [comment]
There's a new doc here as well: https://docs.api7.ai/apisix/key-concepts/plugins#plugins-execution-order

If this answers your question, please update / close the issue. Thanks!
