### ISSUE TITLE
help request: Does the proxy_mirror plugin support mirroring grpc traffic?

### ISSUE THREAD

**Issue by chenwenjun-github** [apache/apisix#9245]
### Description

I use the proxy_mirror plug-in to mirror the http traffic test OK, but the grpc traffic does not take effect, and there is no error reported in the apisix log

If it is not currently supported, can you tell me how to modify it to support it?

![image](https://user-images.githubusercontent.com/46237364/230058841-2f2a1fe6-143b-46e2-a8b7-e919d65ad159.png)
![image](https://user-images.githubusercontent.com/46237364/230058900-7a829f06-b143-462a-b316-53b893f364c8.png)

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by chenwenjun-github** [comment]
![image](https://user-images.githubusercontent.com/46237364/230592071-7ca14b84-df48-493e-8256-86ededb0833b.png)

**Comment by kingluo** [comment]
@chenwenjun-github
APISIX does not support proxy-mirror for grpc yet, although nginx does.

And it's not an easy job to make it work. I just give some points:
1. current proxy_mirror location is filled with proxy_pass directives, i.e. http1 only
2. APISIX enables mirror dynamically, set a flag in the request ctx, but for grpc upstream, it invokes `ngx.exec`, which clears the ctx, so mirror is disabled
3. we need to set up correct parameters like URL before sending it out to the grpc mirror target, otherwise, it will be an error due to the wrong URL `/proxy_mirror`:
![1680966318273](https://user-images.githubusercontent.com/4401042/230728583-d089a6d0-8c90-4e44-af39-d26b985b8410.png)

**Comment by monkeyDluffy6017** [comment]
consider resolved
