### ISSUE TITLE
docs: Add Plugin Metadata in Terminology

### ISSUE THREAD

**Issue by kayx23** [apache/apisix#9261]
### Current State

Plugin metadata doesn't have an associated doc under Terminology

![image](https://user-images.githubusercontent.com/39619599/230586783-eee38281-6008-4dac-94cb-7089b7e86588.png)

### Desired State

Perhaps plugin metadata should have its own doc in terminology too?

**Comment by navendu-pottekkat** [comment]
We can, but IMO, we don't need it because we mention the metadata available for each Plugin in the corresponding Plugin docs. Metadata doesn't have a different meaning here.

Plugin Config needs to have a section here because it is a concept specific to APISIX.

If more people find that this is missing in the docs, we can add it.

**Comment by kayx23** [comment]
Here I was referring to the metadata object one can create with the admin API. It has a "global" effect on plugin instances of the same name. 

Metadata properties set at the plugin level is more granular and has a higher priority over the "global" metadata object. I don't know where this concept was explained in the current doc.

This was before this doc was written https://docs.api7.ai/apisix/key-concepts/plugin-metadata

**Comment by navendu-pottekkat** [comment]
@kayx23 Thanks for clearing that. Makes sense to add it.

**Comment by smileby** [comment]
@pottekkat @kayx23 
Hi, I have made additions to the document and submitted a pull request. Could you please review it to see if there are any issues?  Thank you very much.

[Add Plugin Metadata in Terminology #10702](https://github.com/apache/apisix/pull/10702)
