### ISSUE TITLE
help request: Can i use apisix to replace kourier as a networking layer in Knative????

### ISSUE THREAD

**Issue by MaxChole** [apache/apisix#9352]
### Description

Can i use apisix to replace kourier as a networking layer in Knative?

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Sn0rt** [comment]
If I understand correctly the Kourier is an ingress controller. you can try this 
https://apisix.apache.org/docs/ingress-controller/design/

**Comment by tao12345666333** [comment]
Currently, you can indeed use the APISIX Ingress controller as the traffic entry point for your Kubernetes cluster.

**Comment by PasanBhanu** [comment]
@MaxChole I think you cannot replace kourier. But you can use apisix to route traffic to kourier and let it do the internal routing in knative. 

The main challenge you will face is overriding the host header. Because kourier only works with host header for routing. 

I'm working on a plugin to dynamically change the host header for upstream so it can change the host header before passing to kourier layer. 

You can use proxy-rewrite plugin to either extract function name from url or a different header. 

You can check the code here [https://github.com/PasanBhanu/apisix-knative-kourier-routing-plugin](https://github.com/PasanBhanu/apisix-knative-kourier-routing-plugin)
