### ISSUE TITLE
docs: The `disable plugin` in the current documentation is incorrectly described

### ISSUE THREAD

**Issue by monkeyDluffy6017** [apache/apisix#9359]
Help Wanted. You should review all log plugin docs and update them.

### Current State

The `disable plugin` in the current documentation is incorrectly described
<img width="1032" alt="image" src="https://user-images.githubusercontent.com/9354193/233878752-c632e703-bdc5-4893-a892-d352c4d945a4.png">

### Desired State

it shoud be `delete plugin`

**Comment by Neilblaze** [comment]
@monkeyDluffy6017 I think it's done intentionally, since if the plugin is deleted, it automatically disables it's functionality.

Issue Source → [limit-req](https://apisix.apache.org/docs/apisix/plugins/limit-req/#disable-plugin)

I'm taking this up. Besides, I also see that recurrent changes are required in [grpc-web](https://apisix.apache.org/docs/apisix/plugins/grpc-web/#disable-plugin), [proxy-control](https://apisix.apache.org/docs/apisix/plugins/proxy-control/#disable-plugin), [client-control](https://apisix.apache.org/docs/apisix/plugins/client-control/#disable-plugin), [kafka-proxy](https://apisix.apache.org/docs/apisix/plugins/kafka-proxy/#disable-plugin), [mqtt-proxy](https://apisix.apache.org/docs/apisix/plugins/mqtt-proxy/#disable-plugin), [ext-plugin-pre-req](https://apisix.apache.org/docs/apisix/plugins/ext-plugin-pre-req/#disable-plugin), [ext-plugin-post-resp](https://apisix.apache.org/docs/apisix/plugins/ext-plugin-post-resp/#disable-plugin), [real-ip](https://apisix.apache.org/docs/apisix/plugins/real-ip/#disable-plugin), [cas-auth](https://apisix.apache.org/docs/apisix/plugins/cas-auth/#disable-plugin), [jwt-auth](https://apisix.apache.org/docs/apisix/plugins/basic-auth/#disable-plugin), [key-auth](https://apisix.apache.org/docs/apisix/plugins/key-auth/#disable-plugin), [uri-blocker](https://apisix.apache.org/docs/apisix/plugins/uri-blocker/#disable-plugin), [public-api](https://apisix.apache.org/docs/apisix/plugins/public-api/#disable-plugin), [ip-restriction](https://apisix.apache.org/docs/apisix/plugins/ip-restriction/#disable-plugin), [csrf](https://apisix.apache.org/docs/apisix/plugins/csrf/#disable-plugin), [ua-restriction](https://apisix.apache.org/docs/apisix/plugins/ua-restriction/#disable-plugin), [serverless](https://apisix.apache.org/docs/apisix/plugins/serverless/#disable-plugin).


Changes that need to be added → [Reference_1](https://apisix.apache.org/docs/apisix/plugins/inspect/#disable-plugin) , [Reference_2](https://apisix.apache.org/docs/apisix/plugins/log-rotate/#disable-plugin).

cc: @navendu-pottekkat, @nfrankel

**Comment by LiteSun** [comment]
The delete plugin operation will also disable the plugin.
The disabled plugin operation allows the user to disable the plugin while retaining the configuration information the next time it is enabled.

**Comment by monkeyDluffy6017** [comment]
What about your opinion? @moonming

**Comment by kayx23** [comment]
In a nut shell:
* the verb "disable" should be used to refer to plugin's `_meta.disable` 
* the verb "delete" should be used to refer to removing the corresponding JSON config

Current doc seems to be using `disable` for deletion operation.
```
To disable the limit-req Plugin, you can delete the corresponding JSON configuration 
```

**Comment by moonming** [comment]
refer to https://docs.api7.ai/apisix/getting-started/rate-limiting#disable-rate-limiting

**Comment by navendu-pottekkat** [comment]
@Neilblaze Would you like to take this issue up and open a fix? @kayx23 Do you suggest having both disable and delete in each of the Plugin docs or just the disable?

**Comment by kayx23** [comment]
Just noticed the current doc (as well as the new doc) uses the wording "enable plugin" to refer to the action of adding/creating plugin instance on another APISIX object. I can now see where the "disable plugin" came from...

I think for starter, we can first correct the current "disable plugin" section to "delete plugin" to correspond to the action of adding Json configs. 

As for adding `_meta.disable` details, that's a TBD. it'd be the same usage for every plugin. 

@moonming @monkeyDluffy6017 thoughts?

**Comment by kayx23** [comment]
Hi all, I gave this bit more thought and suggest we update the section to `delete` and not add `disable` section/example here.
