### ISSUE TITLE
bug: `real-ip` attribute `source` does not enforce IP format

### ISSUE THREAD

**Issue by kayx23** [apache/apisix#9493]
### Current Behavior

The field should be used for the originating IP of a client. Currently it doesn't check string format.
![image](https://github.com/apache/apisix/assets/39619599/f67556f7-21b2-4abb-a569-17f0b48b1b3d)

### Expected Behavior

Error out on strings input that are not IPs.

### Steps to Reproduce

```
curl "http://127.0.0.1:9180/apisix/admin/routes" -H "X-API-KEY: xxx" -X PUT -d '
{
  "id": "getting-started-anything",
  "uri": "/anything",
  "upstream" : {
    "type": "roundrobin",
    "nodes": {
      "httpbin.org": 1
    }
  }
}'
```
```
curl http://127.0.0.1:9180/apisix/admin/global_rules/1 -H "X-API-KEY: xxx" -X PUT  -d '{
   "plugins":{
      "real-ip":{
         "source": "http_x_forwarded_for"
      }
   }
}'
```
```
curl "http://127.0.0.1:9080/anything" -H "x_forwarded_for: random-string"
```

### Environment

- APISIX version (run `apisix version`): 3.3

**Comment by Hazel6869** [comment]
@kayx23 Hi, thanks for your issue, we will fix it.   cc @kingluo

**Comment by zccabb** [comment]
Can you assign this problem to me？

**Comment by zccabb** [comment]
You can refer to this isuue #9494 .
The reason is the same.

I believe this may be a bug with httpbin. Firstly, it seems that you are sending the wrong header - it should be x-forwarded-for, not x_forwarded_for. However, it appears that httpbin is still able to process the x_forwarded_for header for the sake of compatibility. It seems possible that there is a bug related to this compatibility feature. You could try the following:

curl http://httpbin.org/anything -H "x-forwarded-for: 1.2.3.111" -v -H 'x_forwarded_for: 1.1.1.1'
Send request without to APISIX. And you will get the same result below:

*   Trying 54.173.69.67:80...
* Connected to httpbin.org (54.173.69.67) port 80 (#0)
> GET /anything HTTP/1.1
> Host: httpbin.org
> User-Agent: curl/7.74.0
> Accept: */*
> x-forwarded-for: 1.2.3.111
> x_forwarded_for: 1.1.1.1
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Wed, 17 May 2023 09:10:57 GMT
< Content-Type: application/json
< Content-Length: 361
< Connection: keep-alive
< Server: gunicorn/19.9.0
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Credentials: true
<
{
  "args": {},
  "data": "",
  "files": {},
  "form": {},
  "headers": {
    "Accept": "*/*",
    "Host": "httpbin.org",
    "User-Agent": "curl/7.74.0",
    "X-Amzn-Trace-Id": "Root=1-64649a1f-23d29ac7700c8fc15eac7054"
  },
  "json": null,
  "method": "GET",
  "origin": "1.2.3.111, 61.232.56.241,1.1.1.1",
  "url": "http://httpbin.org/anything"
}

**Comment by kayx23** [comment]
ok, I'll leave it for you to decided if this is a bug or something to improve on on the engineering side.

I noticed these issues when looking into an issue for another user: https://github.com/apache/apisix/issues/9494#issuecomment-1550842387

**Comment by shreemaan-abhishek** [comment]
@kayx23, the `source` attribute expects nginx variables, not IP addresses directly. The correct usage would be to prefix the ngx variable with a `$`. Like so:

```bash
curl http://127.0.0.1:9180/apisix/admin/global_rules/1 -H "X-API-KEY: xxx" -X PUT  -d '{
   "plugins":{
      "real-ip":{
         "source": "$http_x_forwarded_for"
      }
   }
}'

```

**Comment by shreemaan-abhishek** [comment]
@kayx23, that's because of the header that you are passing (`-H "x_forwarded_for: random-string"`). Try removing it once.

**Comment by kayx23** [comment]
But that is the whole point... APISIX does not check what is passed. Here there should be an input checker.

**Comment by Sn0rt** [comment]
take a look

**Comment by Revolyssup** [comment]
@kayx23 Actually the logic in real-ip plugin allows this to be IPV4,IPV6 or just a hostname like localhost. Here random-string could literally be a host name so it is being allowed. So the question here is whether we want to allow hostnames like this or keep it only to IPV4 and IPV6. If hostnames can be allowed, then this issue can be closed.

**Comment by kayx23** [comment]
I wasn't aware the hostname is allowed. It's not mentioned in docs. 

Does allowing for host name make sense though? The plugin is called real **IP**. If allowing for hostname is the intended behaviour, then we can close this issue and perhaps update the [documentation](https://apisix.apache.org/docs/apisix/plugins/real-ip/).

**Comment by Revolyssup** [comment]
> I wasn't aware the hostname is allowed. It's not mentioned in docs.
> 
> Does allowing for host name make sense though? The plugin is called real **IP**. If allowing for hostname is the intended behaviour, then we can close this issue and perhaps update the [documentation](https://apisix.apache.org/docs/apisix/plugins/real-ip/).

I think we can close this issue and you can create a subsequent issue updating the doc from this comment https://github.com/apache/apisix/blob/112ff549b63bfec13cdb75b0a711a7e38f2caa24/apisix/core/utils.lua#L178

**Comment by moonming** [comment]
fixed by https://github.com/apache/apisix/pull/9905
