### ISSUE TITLE
help request: Which one is the best practice for integrating the coraza WAF, a Lua plugin or a go runner plugin?

### ISSUE THREAD

**Issue by bingfengfeifei** [apache/apisix#9632]
### Description

If I want to integrate a WAF into apisix, such as coraza, a WAF written in Golang, the best practice would be to write a plugin in Lua, export coraza as a C language interface, and then call the C language interface through FFI, or directly integrate coraza through a go runner. Does either of these methods have an impact on detection speed? Will the go runner form be significantly slower than the Lua method?

### Environment

- APISIX version (run `apisix version`): 3.3.0
- Operating system (run `uname -a`): Linux apisix-5fc4c5bf47-kbkwp 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): nginx version: openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):3.5.0
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by zccabb** [comment]
I think Integrating via a Go runner - This will likely be slower than the above 2 options since:
- When you configure a plugin runner in APISIX, APISIX will treat the plugin runner as a child process of its own. So there will be inter-process communication overhead.

There may be some problems with what I have stated. For details, you can refer to the documentation about Go Plugin:
https://apisix.apache.org/zh/docs/go-plugin-runner/getting-started/
![image](https://github.com/apache/apisix/assets/76942195/301489e4-7770-4292-a4a1-94b1e73b1022)
The diagram above shows the workflow of APISIX on the left, while the plugin runner on the right is responsible for running external plugins written in different languages. apisix-go-plugin-runner is one such runner that supports Go.

**Comment by Sn0rt** [comment]
This is an exciting requirement, and I think this requirement can complement a functional shortcoming of APISIX.

Let's see how to achieve this requirement.

**Comment by monkeyDluffy6017** [comment]
Please try this one: https://github.com/potats0/apisix-coraza
