### ISSUE TITLE
help request: discovery fetch_interval?

### ISSUE THREAD

**Issue by shallowinggg** [apache/apisix#9641]
### Description

I want to integrate our inner used service registry with apisix and find the document [Integration service discovery registry](https://apisix.apache.org/docs/apisix/discovery/). The doc use configuration `fetch_interval: 30` as default, will this cause service unavailable when deployment applications (old nodes offline and new nodes deployed successfully within 30s)？ Shorter fetch intervals may influence service registry,  can u has some good solutions for this? Thx

### Environment

no

**Comment by Revolyssup** [comment]
For consul, the doc suggest 3-5 seconds. For registries like Kubernetes, a push based model is used by establishing a watch stream so it depends on registry to registry. 
If your service registry supports streaming updates via watch then you can avoid polling altogether. 
Otherwise you can keep the polling timeout as low as 3-5 seconds.

And to answer your question, Yes there will be downtime if APISIX is not updated from registry and that's why a 3-5 second timeout is helpful. If your registry has some other API which can be used to figure out "Last-updates" then instead of fetching full registry on interval, you can first check if there were any updates. The implementation will vary from registry to registry.
