### ISSUE TITLE
help request: opentelemetry plugin with grpc server upstream can't send trace

### ISSUE THREAD

**Issue by bai-ming** [apache/apisix#9667]
### Description

I create a route for grpc server, 
the config like this
![image](https://github.com/apache/apisix/assets/85221235/5c808382-3271-4bf7-ac9b-7bcb0eb01cc8)
I can get the correct response but the trace send failed.
![image](https://github.com/apache/apisix/assets/85221235/8a959e0b-60e3-4ae2-bb11-804b0cfa18e5)
At first, I deleted the grpc-translate plugin but the trace still send failed
![image](https://github.com/apache/apisix/assets/85221235/a8c7bdb0-76b4-4c01-a707-ae65fd22b3b7)
Next, I change a new upstream with the scheme is HTTP.
![image](https://github.com/apache/apisix/assets/85221235/3a48853d-3a92-4c83-a113-528558764fe6)
At this time, the trace send successfully.
So I wonder if there is something wrong between opentelemetry plugin and grpc server? Or I have some problems with my configuration?

### Environment

- APISIX version (run `apisix version`): 3.3.0
- Operating system (run `uname -a`): 4.15.0-204-generic #215-Ubuntu SMP Fri Jan 20 18:24:59 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):nginx version: openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.5.0
- APISIX Dashboard version, if relevant: 3.0.1
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Revolyssup** [comment]
@bai-ming Opentelemetry Plugin only supports binary-encoded [OLTP over HTTP](https://opentelemetry.io/docs/reference/specification/protocol/otlp/#otlphttp).

**Comment by bai-ming** [comment]
emmm, but i use the grpc-transcode plugin to translate it, it still dosen't work. Or tracer only works with http upstream?

**Comment by Revolyssup** [comment]
Actually grpc shouldn't be a problem here. gRPC is on top of HTTP and the request is in place modified in the grpc-transcode plugin. Just to confirm your issue, the problem is `scheme` field on the upstream, right?
What happens when you use the grpc transcode plugin as usual but set the upstream scheme to `http` ?

**Comment by Revolyssup** [comment]
@bai-ming While using the scheme:grpc , the context of the original request is destroyed so opentelemetry plugin wont work with it.

**Comment by Revolyssup** [comment]
@bai-ming By default the priority of opentelemetry < priority of grpc transcode so when the request will be processed by opentelemetry plugin. It would have been modified according to the grpc transcode plugin. 
Will you try with updating the priority in config-default.yaml so that opentelemetry has lower number? and see if the error continues

**Comment by Revolyssup** [comment]
@bai-ming This issue has been fixed here - https://github.com/apache/apisix/pull/9606

**Comment by Revolyssup** [comment]
fixed here - https://github.com/apache/apisix/pull/9606
