### ISSUE TITLE
bug: PURGE method make api gateway return http status code 404

### ISSUE THREAD

**Issue by namdiag** [apache/apisix#9688]
### Current Behavior

A route has proxy_cache config. If the cache data isn't existed yet, call to the route URL with PURGE method will cause the apisix return 404 error on this route.

There are 2 severe problems that including security over this issue:
- Although PURGE method has been added to  http-block-method and not including in http-allow-methods,  when user call Api gateway it's indeed return response with status code 405 but the cache delete is still happening. A severe security issue with this problem? How can cache still get deleted on API Gateway even though it's return status code 405 Method Not Allow?
- Running PURGE method against a route that hasn't been cache yet but has proxy_cache config make every call after that with different http method like GET, POST return 404, the error likely on function run_plugin()

### Expected Behavior

- PURGE method can be block and when call from outside world it should not cause cache delete
- PURGE method when call against route that has cache config but cache data doesn't exist yet should be ok, not cause error on subsequence normal method call

### Error Logs

```
apisix 42.112.56.241 - - [19/Jun/2023:02:35:49 +0000] staging.mydomain.com "PURGE / HTTP/2.0" 405 0 0.000 "-" "curl/8.0.1" - - - "http://staging.mydomain.com"
apisix 42.112.56.241 - - [19/Jun/2023:02:35:51 +0000] staging.mydomain.com "PURGE / HTTP/2.0" 405 225 0.000 "-" "curl/8.0.1" - - - "http://staging.mydomain.com"   
apisix 2023/06/19 01:52:26 [warn] 50#50: *497235 [lua] plugin.lua:1102: run_plugin(): proxy-cache exits with http status code 404, client: 42.112.56.241, server: _, request: "GET /" 
```

### Steps to Reproduce

1. create API Route and Upstream through Apisix Ingress with host: `staging.mydomain.com`,  this Ingress contain these annotations:

> k8s.apisix.apache.org/http-allow-methods: GET,POST,PUT,PATCH,DELETE,OPTIONS,HEAD
> k8s.apisix.apache.org/http-block-method: PURGE
> k8s.apisix.apache.org/plugin-config-name: proxy-cache-config

2. Run -v 
here is the response
```
* Using Stream ID: 1 (easy handle 0x55a567d39e10)
> PURGE / HTTP/2
> Host: staging.mydomain.com
> user-agent: curl/8.0.1
> accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
< HTTP/2 405
< date: Mon, 19 Jun 2023 02:35:51 GMT
< content-type: text/html; charset=utf-8
< content-length: 225
< server: APISIX/3.3.0
<
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>openresty</center>
<p><em>Powered by <a href="https://apisix.apache.org/">APISIX</a>.</em></p></body>
</html>
* Connection #0 to host staging.mydomain.com left intact
```

### Environment

- APISIX version (run `apisix version`): 3.3.0
- Operating system (run `uname -a`): Linux apisix-8b95d7d5c-lv5bf 5.15.89+ #1 SMP Sat Mar 18 09:27:02 UTC 2023 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): nginx version: openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.5.2
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Revolyssup** [comment]
@namdiag 
1. For the first issue around 405, the annotation `k8s.apisix.apache.org/http-allow-methods` is supported only on response-rewrite plugin. Do you have that plugin configured as well?
2. For the issue around 404, that is by design. Because it doesn't make sense to PURGE something that doesn't exist. Returning 200 in that case will be misleading. Client should make sure something exists before it tries to PURGE it.

**Comment by namdiag** [comment]
> @namdiag
> 
> 1. For the first issue around 405, the annotation `k8s.apisix.apache.org/http-allow-methods` is supported only on response-rewrite plugin. Do you have that plugin configured as well?
> 2. For the issue around 404, that is by design. Because it doesn't make sense to PURGE something that doesn't exist. Returning 200 in that case will be misleading. Client should make sure something exists before it tries to PURGE it.

1. I believe you're not correct about the http-allow-methods only available on response-rewrite plugin, please double check the document of response-rewrite plugin and also how to create a route and enable the http-allow-method here https://apisix.apache.org/docs/apisix/admin-api/#route . The annotation is no different than manual create route and add parameter to it.
2. Please reread the problem, it's not about how it's response, but how it return error on every subsequence call with other method like GET, POST, meaning the PURGE method which can call from outside world can cause total error on this routes,  Thus render the proxy_cache plugin useless. make API Gateway panic.

**Comment by Revolyssup** [comment]
1. The only place where the annotation `http-allow-methods` is used inside ingress-controller is here - https://github.com/apache/apisix-ingress-controller/blob/32c07516b6bf2fe8ff86ecdf65ee04a7afc0c535/pkg/providers/ingress/translation/annotations/plugins/http_method.go#L41, which is configuring response-rewrite plugin. Also to clarify, the parameters passed in the annotation `http-allow-methods` do not correspond to the `methods` field passed in route configuration. 

2. I cannot reproduce this issue on either memory or disk. Following this https://apisix.apache.org/docs/apisix/plugins/proxy-cache/, I create a route and perform PURGE resulting in 404. Then I do GET and it succeeds.  The only place where proxy-cache returns 404 from APISIX's end is on PURGE. Otherwise the statuscode is what's returned from upstream. And since in case of PURGE, no state change takes place, this shouldn't be an issue. I am still looking into it. Meanwhile Can you show the response headers on the subsequent GET requests which are returning 404? @namdiag

**Comment by Revolyssup** [comment]
@namdiag Were you able to resolve the issue?

**Comment by namdiag** [comment]
@Revolyssup 
1. It's indeed as you mention that the ingress resource with annotation http-allow-methods is actually use response-rewrite plugin, so I may need to use apisixRoutes instead
2. I still got the error on subsequence request after PURGE, you don't have the error maybe because you don't use plugin annotation on ingress resource. Please try to use the plugin annotation here if you have time https://apisix.apache.org/docs/ingress-controller/concepts/annotations/ . 
For my case, i found the ease of using ingress resource with annotation so, i still in trial with it for now, and use apisixRoutes later

**Comment by Revolyssup** [comment]
@namdiag Can you also show the Proxy config named proxy-cache-config that you have referenced in the annotation?
